// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "products",
    "version": "0.0.1"
  },
  "paths": {
    "/product": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "Products"
        ],
        "operationId": "getProducts",
        "parameters": [
          {
            "minimum": 1,
            "type": "integer",
            "format": "int32",
            "default": 100,
            "description": "Количество sku к возвращению",
            "name": "count",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "default": 0,
            "description": "После какого sku начать вывод",
            "name": "start_after_sku",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/product"
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/product/{sku}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "Products"
        ],
        "operationId": "getProduct",
        "parameters": [
          {
            "minimum": 1,
            "type": "integer",
            "format": "int64",
            "description": "Информация о продукте",
            "name": "sku",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/product"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "description": "Represents general error in the API response",
      "type": "object",
      "title": "General error",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "x-isnullable": false
        },
        "message": {
          "description": "the message of this error",
          "type": "string",
          "x-isnullable": false
        }
      }
    },
    "product": {
      "type": "object",
      "required": [
        "sku",
        "name",
        "price"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "price": {
          "type": "integer",
          "format": "int32"
        },
        "sku": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "X-API-KEY",
      "in": "header"
    }
  },
  "tags": [
    {
      "name": "Products"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "products",
    "version": "0.0.1"
  },
  "paths": {
    "/product": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "Products"
        ],
        "operationId": "getProducts",
        "parameters": [
          {
            "minimum": 1,
            "type": "integer",
            "format": "int32",
            "default": 100,
            "description": "Количество sku к возвращению",
            "name": "count",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "default": 0,
            "description": "После какого sku начать вывод",
            "name": "start_after_sku",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/product"
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/product/{sku}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "tags": [
          "Products"
        ],
        "operationId": "getProduct",
        "parameters": [
          {
            "minimum": 1,
            "type": "integer",
            "format": "int64",
            "description": "Информация о продукте",
            "name": "sku",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/product"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "description": "Represents general error in the API response",
      "type": "object",
      "title": "General error",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "x-isnullable": false
        },
        "message": {
          "description": "the message of this error",
          "type": "string",
          "x-isnullable": false
        }
      }
    },
    "product": {
      "type": "object",
      "required": [
        "sku",
        "name",
        "price"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "price": {
          "type": "integer",
          "format": "int32"
        },
        "sku": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "X-API-KEY",
      "in": "header"
    }
  },
  "tags": [
    {
      "name": "Products"
    }
  ]
}`))
}
