// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package animals

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Animal struct {
	ID       int64            `json:"id"`
	Nickname string           `json:"nickname"`
	Birthday pgtype.Timestamp `json:"birthday"`
	Weight   int32            `json:"weight"`
}
