// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package animals

import (
	"context"
)

type Querier interface {
	GetAnimal(ctx context.Context, id int64) (Animal, error)
	Insert(ctx context.Context, arg InsertParams) error
	ListAnimals(ctx context.Context) ([]Animal, error)
}

var _ Querier = (*Queries)(nil)
