// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"log"
	"os"

	"github.com/go-openapi/loads"
	flags "github.com/jessevdk/go-flags"

	swaggerserversrv "gitlab.ozon.dev/go/classroom-20/experts/product-service/internal/app/http/server"
	"gitlab.ozon.dev/go/classroom-20/experts/product-service/internal/app/http/server/operations"
	"gitlab.ozon.dev/go/classroom-20/experts/product-service/internal/infra/repository/products"
	"gitlab.ozon.dev/go/classroom-20/experts/product-service/internal/infra/repository/skus"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	swaggerSpec, err := loads.Embedded(swaggerserversrv.SwaggerJSON, swaggerserversrv.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewProductsAPI(swaggerSpec)
	server := swaggerserversrv.NewServer(api)
	defer server.Shutdown()

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "products"
	parser.LongDescription = swaggerSpec.Spec().Info.Description
	server.ConfigureFlags()
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	server.ConfigureAPI()

	if !skus.IsSkusReady() || !products.IsProductsReady() {
		panic("no data loaded")
	}

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
