// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetProductsParams creates a new GetProductsParams object
// with the default values initialized.
func NewGetProductsParams() GetProductsParams {

	var (
		// initialize parameters with default values

		countDefault         = int32(100)
		startAfterSkuDefault = int64(0)
	)

	return GetProductsParams{
		Count: &countDefault,

		StartAfterSku: &startAfterSkuDefault,
	}
}

// GetProductsParams contains all the bound params for the get products operation
// typically these are obtained from a http.Request
//
// swagger:parameters getProducts
type GetProductsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Количество sku к возвращению
	  Minimum: 1
	  In: query
	  Default: 100
	*/
	Count *int32
	/*После какого sku начать вывод
	  In: query
	  Default: 0
	*/
	StartAfterSku *int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetProductsParams() beforehand.
func (o *GetProductsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qCount, qhkCount, _ := qs.GetOK("count")
	if err := o.bindCount(qCount, qhkCount, route.Formats); err != nil {
		res = append(res, err)
	}

	qStartAfterSku, qhkStartAfterSku, _ := qs.GetOK("start_after_sku")
	if err := o.bindStartAfterSku(qStartAfterSku, qhkStartAfterSku, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCount binds and validates parameter Count from query.
func (o *GetProductsParams) bindCount(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetProductsParams()
		return nil
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("count", "query", "int32", raw)
	}
	o.Count = &value

	if err := o.validateCount(formats); err != nil {
		return err
	}

	return nil
}

// validateCount carries on validations for parameter Count
func (o *GetProductsParams) validateCount(formats strfmt.Registry) error {

	if err := validate.MinimumInt("count", "query", int64(*o.Count), 1, false); err != nil {
		return err
	}

	return nil
}

// bindStartAfterSku binds and validates parameter StartAfterSku from query.
func (o *GetProductsParams) bindStartAfterSku(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetProductsParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("start_after_sku", "query", "int64", raw)
	}
	o.StartAfterSku = &value

	return nil
}
