// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gitlab.ozon.dev/go/classroom-20/experts/product-service/internal/app/http/model"
)

// GetProductOKCode is the HTTP code returned for type GetProductOK
const GetProductOKCode int = 200

/*
GetProductOK A successful response.

swagger:response getProductOK
*/
type GetProductOK struct {

	/*
	  In: Body
	*/
	Payload *model.Product `json:"body,omitempty"`
}

// NewGetProductOK creates GetProductOK with default headers values
func NewGetProductOK() *GetProductOK {

	return &GetProductOK{}
}

// WithPayload adds the payload to the get product o k response
func (o *GetProductOK) WithPayload(payload *model.Product) *GetProductOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get product o k response
func (o *GetProductOK) SetPayload(payload *model.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetProductDefault An unexpected error response.

swagger:response getProductDefault
*/
type GetProductDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewGetProductDefault creates GetProductDefault with default headers values
func NewGetProductDefault(code int) *GetProductDefault {
	if code <= 0 {
		code = 500
	}

	return &GetProductDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get product default response
func (o *GetProductDefault) WithStatusCode(code int) *GetProductDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get product default response
func (o *GetProductDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get product default response
func (o *GetProductDefault) WithPayload(payload *model.Error) *GetProductDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get product default response
func (o *GetProductDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
