// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gitlab.ozon.dev/go/classroom-20/experts/product-service/internal/app/http/model"
)

// GetProductsOKCode is the HTTP code returned for type GetProductsOK
const GetProductsOKCode int = 200

/*
GetProductsOK A successful response.

swagger:response getProductsOK
*/
type GetProductsOK struct {

	/*
	  In: Body
	*/
	Payload []*model.Product `json:"body,omitempty"`
}

// NewGetProductsOK creates GetProductsOK with default headers values
func NewGetProductsOK() *GetProductsOK {

	return &GetProductsOK{}
}

// WithPayload adds the payload to the get products o k response
func (o *GetProductsOK) WithPayload(payload []*model.Product) *GetProductsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get products o k response
func (o *GetProductsOK) SetPayload(payload []*model.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*model.Product, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
GetProductsDefault An unexpected error response.

swagger:response getProductsDefault
*/
type GetProductsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewGetProductsDefault creates GetProductsDefault with default headers values
func NewGetProductsDefault(code int) *GetProductsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetProductsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get products default response
func (o *GetProductsDefault) WithStatusCode(code int) *GetProductsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get products default response
func (o *GetProductsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get products default response
func (o *GetProductsDefault) WithPayload(payload *model.Error) *GetProductsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get products default response
func (o *GetProductsDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
